#!/bin/bash

function build {
    cd $1
    for file in *
    do

        prefix=$3
        export AP="$prefix"
        export include="$AP/kparse"

        if grep -q "@" <<< "$file" 
        then
            continue

        elif [[ -d $file ]] && [[ '.' != $file ]] && [[ '..' != $file ]]
        then

            if [[ $2 = '/' ]]
            then
                mkdir $prefix/build/$2/$file 
                build $file $file $3/..
                continue
            else
                build $file $2/$file $3/..
            fi
            
        fi

        if [[ $file = 'index.html' ]]; then
            if [[ $2 != '/' ]]
            then
                $prefix/kparse $file > $prefix/build/$2/$file
            else
                $prefix/kparse $file > ../build/$file
            fi
        else

            if [[ $2 != '/' ]]
            then
                mkdir $prefix/build/$2/${file%.html}
                touch $prefix/build/$2/${file%.html}/index.html
                $prefix/kparse $file > $prefix/build/$2/${file%.html}/index.html
            else
                mkdir ../build/${file%.html}
                touch ../build/${file%.html}/index.html
                $prefix/kparse $file > ../build/${file%.html}/index.html
            fi
            
        fi

    done
    cd ..
}

if [[ -z $1 ]]; then
    echo -e "Klink - version 1.0" 
    echo    "Usage: ./klink <dir> <port>"
    echo -e "\tdir: directory to be parsed"
    echo -e "\tport: (optional) port to be served"
    exit
fi


if [[ -d build ]]; then
    rm -rf build
fi

mkdir build
build $1 '/' ..

if [[ -n $2 ]]; then
    php -S localhost:$2 -t build
fi